version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - springboot-net

  flyway:
    image: flyway/flyway:latest
    container_name: flyway
    depends_on:
      - postgres
    command: -url=jdbc:postgresql://postgres:5432/mydatabase -user=postgres -password=postgres -connectRetries=10 migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    networks:
      - springboot-net

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    command: redis-server --requirepass renos1987
    ports:
      - "6379:6379"
    networks:
      - springboot-net

  springboot-app:
    container_name: springboot-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
      - flyway
    ports:
      - "9088:8080"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: renos1987
    networks:
      - springboot-net

networks:
  springboot-net:
    driver: bridge

volumes:
  postgres-data:
